config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :tasks, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates_presence_of :title
  validate :future_completed_date

  private

  def future_completed_date
    self.errors.add(:completed, "Back to the future?))") if !completed.blank? && completed < Date.today
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@todo_tasks = Task.all
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
		@todo_task = Task.new
	end

	def create
		@todo_task = Task.create(task_params)
		@todo_tasks = Task.all
	end

	def edit
		@todo_task = Task.find(params[:id])
		render :new
	end

	def update
		@todo_task = Task.find(params[:id])
		@todo_task.update_attributes(task_params)
		@todo_tasks = Task.all
		render :create
	end

	def destroy
		@todo_task = Task.find(params[:id])
		@todo_task.destroy
		@todo_tasks = Task.all
	end

	private
	def task_params
		params.require(:task).permit(:title, :note, :completed)
	end

	private
	def apply
		if @todo_task.save
			@todo_tasks = Task.all
			render :create
		else
			render :new
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Todo for Azure
	= stylesheet_link_tag    "application", media: "all"
	= javascript_include_tag "application"
	= csrf_meta_tags
%body
	.row-fluid
		.span10.offset1
			.hero-unit.text-center
				%h2
					Todo Application for Azure
				%p
					Welcome to the todo's start page!
				= link_to 'New task', new_task_path,  class:  'btn btn-primary', remote: true
	= yield

app/views/pages/home.html.haml
#task-list.container
  = render partial: 'tasks/task_list', locals: {tasks: @todo_tasks}
#modal.modal.fade

app/views/tasks/_task_form.html.haml
.modal-header
  %h1
    = task.new_record? ? 'New Task' : "Edit #{task.title}"
  = simple_form_for task, class: 'clearfix', remote: true do |form|
    .modal-body
      = form.input :title
      = form.input :note
      = form.input :completed, as: :string, input_html: {class: 'datepicker'}
    .modal-footer
      = form.submit 'Save', class: 'btn btn-primary'

app/views/tasks/_task_list.html.haml
- if tasks.empty?
    %div.text-warning No task. Stolen by Russian hackers for Hillary!
    %p
    / = link_to image_tag( '/assets/images/noItems.jpg'), 'http://www.google.com'
    %img{:src => asset_path("noItems.jpg")}/
- else
    %table.table.table-hover.table-bordered
        %thead
            %tr
                %th Title
                %th Note
                %th Created at
                %th Completed?
                %th What to do
        %tbody
            - tasks.each do |item|
                %tr
                    %td
                        %strong= item.title
                    %td
                        %strong= item.note
                    %td.text-info= item.created_at
                    %td.text-success= item.completed
                    %td
                        = link_to task_path(item), remote: true, method: :delete do
                            %i.icon-remove-circle
                        = link_to edit_task_path(item), remote: true do
                            %i.icon-edit

app/views/tasks/create.js.erb
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @todo_tasks}) %>');
$('#modal').modal('hide');

app/views/tasks/new.js.erb
m = $('#modal');
// m.addDatePicker();
m.html('<%= j(render partial: 'task_form', locals: {task: @todo_task}) %>');
m.modal('show');
$('#modal').addDatePicker()